### ISSUE TITLE
.media-wrapper is a little too narrow on desktop

### ISSUE THREAD

**Issue by jayseeg** [jayseeg/brownFox#65]
.media-wrapper is the class of the div that keeps all of the content centered in the site,... it should probably be the same width as the header. Please respond with the updated css for .media-wrapper.

it's currently:
```
.media-wrapper {
  margin: 0 auto;
  max-width: 800px;
}
```

**Comment by lbecerra99** [comment]
.media-wrapper {
  margin: 0 auto;
  max-width: 1000px;
 min-width: 320px;
}
these are the parameters as of now for the nav in my css

**Comment by jayseeg** [comment]
Good call. I'll get that plugged in for you.

**Comment by lbecerra99** [comment]
thanks! anything else on this issue?

**Comment by jayseeg** [comment]
nope, I just need to plug in the changes
