### ISSUE TITLE
The contact page needs some love on the spacing of the form elements & their titles

### ISSUE THREAD

**Issue by jayseeg** [jayseeg/brownFox#66]
http://173.255.211.63/contact.php

what margin do you want me to apply to the p tags?

**Comment by lbecerra99** [comment]
i dont think i want the lengths of the bars to go all the way across by im not sure how to fix that. Also pad everything like 1.5em. is there a way we can make the message box big by default. 

do we want a cool thing happening in our background-considering our overall website is a bit bland? or ideas on how do you think we should make our website pop?

**Comment by jayseeg** [comment]
Good question about making it pop,...
What about something like this: https://codepen.io/0xc0defeed/pen/gBumd
maybe mess with the colors and some of the other properties till it looks unique & fits your vision for the site?

**Comment by jayseeg** [comment]
Something like a maximum width for the bars?

Is the padding meant to space the bars (margin), or to make the bars thicker (padding)? (Sorry for being dense,... I just want to make sure I know what you're thinking.)

We can set columns & rows on the main text box to make it bigger,... good idea,... it's pretty small.

**Comment by lbecerra99** [comment]
padding meant to space the bars and the text boxes but top and bottom margins may do the thing better

**Comment by jayseeg** [comment]
cool, I'll try with margin,... I think it'll do the trick

**Comment by lbecerra99** [comment]
@import "compass/css3";
$one: rgba(236, 208, 120, 1);
$two:  #3EA377;
$three: #295F88;
$four: #16486F;
$five: rgba(83, 119, 122, 1);

body {
  background-image:
    linear-gradient(135deg,
    transparent 84px,
    $two 84px, $two 100px,
    $one 100px, $one 106px,
    $three 106px, $three 120px,
    $one 121px, $one 127px,
    $four 127px, $four 142px,
    $one 142px, $one 148px,
    $five 148px, $five 163px,
    $one 163px, $one 168px,
    $two 169px
    ),
    
    linear-gradient(135deg,
    $two 15px, $two,
    $one 15px, $one 21px,
    $three 21px, $three 36px,
    $one 36px, $one 42px,
    $four 42px, $four 57.5px,
    $one 57px, $one 63px,
    $five 63px, $five 78px,
    $one 78px, $one 84px,
    transparent 84px, transparent 99px
    );
  
  background-size: 120px 120px;
}




just screwed around with the colors, this should look good. 
however i cant verify it does because when i plugged it into other codepens nothing showed up.... and i wasnt about to troubleshoot that ish.
