### ISSUE TITLE
The text on the copy template is a little hard to read

### ISSUE THREAD

**Issue by jayseeg** [jayseeg/brownFox#67]
http://173.255.211.63/copy.template.html

The text is probably too tight (search for mdn line-height), and the font is probably a little too small.

**Comment by lbecerra99** [comment]
p{
  line-height:1.4;
 font-size:20px;
}

tell me if this is too big or oddly spaced out. 
if its not too big increase the header size to something like 35px

**Comment by jayseeg** [comment]
awesome,... will do

**Comment by lbecerra99** [comment]
thanks! anything else on this issue?

**Comment by jayseeg** [comment]
should be good

**Comment by lbecerra99** [comment]
sweet
